# docker-compose
# used for MyYoutube microservices
version: '2'

services:
  api:
    build: api
    links:
      - db
    ports:
      - "5000:5000"
    networks:
      youtube_net:
        ipv4_address: "172.16.0.10"
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: youtube
      MYSQL_DATABASE: youtube
      MYSQL_USER: youtube
      MYSQL_PASSWORD: youtube
    ports:
      - "9906:3306"
    command: --init-file /youtube_v2.sql
    volumes:
      - ./resources/youtube_v2.sql:/youtube_v2.sql
    networks:
      youtube_net:
        ipv4_address: "172.16.0.11"

networks:
  youtube_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24